### ISSUE TITLE
embed选 word2vec

### ISSUE THREAD

**Issue by BarryZM** [yongzhuo/Keras-TextClassification#1]
楼主您好，请问可以加一个embed选word2vec的demo么？我用word2vec embedding一直报错

**Comment by yongzhuo** [comment]
sample已上传，建议你重新下载，具体的bert、word2vec（char or word）、random（char or word）的embedding请参照test/目录下文件

**Comment by BarryZM** [comment]
跑通了，感谢大佬，灰常感谢。
