### ISSUE TITLE
个人意见，不在sentence2idx进行extract_chinese

### ISSUE THREAD

**Issue by li1191863273** [yongzhuo/Keras-TextClassification#10]
因为extract_chinese会去除掉文本中的标点符号 或者 换行符 空格之类的

有些词向量已经包含这一部分信息，感觉去掉了会破坏文本的结构信息

**Comment by yongzhuo** [comment]
认为去除标点符号还是有必要的:
1.提高泛化性等，
2.如基本每个句子都会有逗号等，几乎没什么信息
3.短文本分类中应该不重要
4.除非是情感分析等
