### ISSUE TITLE
感觉用不到词向量加载权重

### ISSUE THREAD

**Issue by li1191863273** [yongzhuo/Keras-TextClassification#12]
使用BertEmbedding

graph的create_model方法
最下面，向word_embedding的model加载权重
    # 构建网络层
        self.word_embedding = Embeddings(hyper_parameters=hyper_parameters)
        if os.path.exists(self.path_fineture) and self.trainable:
            self.word_embedding.model.load_weights(self.path_fineture)
            print("load path_fineture ok!")
        self.model = None

但是感觉加载了也不会用self.word_embedding.model

例如TextCNNGraph，直接使用self.word_embedding的输入输出
embedding = self.word_embedding.output
self.model = Model(inputs=self.word_embedding.input, outputs=output)

**Comment by yongzhuo** [comment]
是不会self.word_embedding.output这样引用，
但是实际上这个的作用是加载微调后的bert、xlnet、albert或者是word2vec模型

**Comment by li1191863273** [comment]
你看一下extCNNGraph
下面的代码是直接引用的
self.model = Model(inputs=self.word_embedding.input, outputs=output)

**Comment by yongzhuo** [comment]
你的意思是graph的引用如果没有改成self.word_embedding.model.input
和self.word_embedding.model.output，预测的时候相当于还是用以前的模型,而不是微调的模型?

**Comment by li1191863273** [comment]
现在TextCnn引用是这么这么写的
self.model = Model(inputs=self.word_embedding.input, outputs=output)

我理解是在用以前的模型，没有加载微调后的模型

**Comment by li1191863273** [comment]
我明白了，这样也能加载到微调后的模型
