### ISSUE TITLE
data目录下embeddings应该是没有上传完全

### ISSUE THREAD

**Issue by liyingkun1237** [yongzhuo/Keras-TextClassification#13]
文档中：
- embeddings
       - chinese_L-12_H-768_A-12/(取谷歌预训练好点的模型,已经压缩上传,
                                  keras-bert还可以加载百度版ernie(需转换，[https://github.com/ArthurRizar/tensorflow_ernie](https://github.com/ArthurRizar/tensorflow_ernie)),
                                  哈工大版bert-wwm(tf框架，[https://github.com/ymcui/Chinese-BERT-wwm](https://github.com/ymcui/Chinese-BERT-wwm))
       - albert_base_zh/(brightmart训练的albert, 地址为https://github.com/brightmart/albert_zh)
       - chinese_xlnet_mid_L-24_H-768_A-12/(哈工大预训练的中文xlnet模型[https://github.com/ymcui/Chinese-PreTrained-XLNet],24层)
       - term_char.txt(已经上传, 项目中已全, wiki字典, 还可以用新华字典什么的)
       - term_word.txt(未上传, 项目中只有部分, 可参考词向量的)
       - w2v_model_merge_short.vec(未上传, 项目中只有部分, 词向量, 可以用自己的)
       - w2v_model_wiki_char.vec(已上传百度网盘, 项目中只有部分, 自己训练的维基百科字向量, 可以用自己的)

实际：
![image](https://user-images.githubusercontent.com/10301126/66976591-09862f80-f0d5-11e9-8cd1-1e778d9cb873.png)

**Comment by yongzhuo** [comment]
github有空间限制，这些预训练模型等都可以在网上找到，地址已给出

**Comment by liyingkun1237** [comment]
嗯 感谢分享了
