### ISSUE TITLE
同样的验证集在训练和预测的时候获得的准确率不同

### ISSUE THREAD

**Issue by Veyronl** [yongzhuo/Keras-TextClassification#15]
训练时验证集的准确率为93%,但是在测试阶段,用pred_tet获得准确率只有41%,使用的是Capsule和TextCNN,10月28日左右的模型,正在排查问题

**Comment by yongzhuo** [comment]
超参数可以贴一下吗，我看看可以复现么

**Comment by Veyronl** [comment]
![image](https://user-images.githubusercontent.com/46363468/68104326-a0484e00-ff15-11e9-832f-412352ac8299.png)
非常感谢您的回复

**Comment by Veyronl** [comment]
模型保存和加载看着都没有问题,
同时还有另外1个小疑问,关于不同模型的Dropout,在预测时,不应该都为1吗?保存的json文件,还不为1.是否需要调整呢?(跟上述问题无关,,因为手动修改,对结果预测并无影响)

**Comment by yongzhuo** [comment]
请问你有用自己的词向量吗，项目中自带的词向量只有50个word，所以基本上所有的句子都是"unk"，这样训练的结果就多是随机的random

**Comment by Veyronl** [comment]
是自己的词向量,而且用predict的时候无论用训练集还是验证集中的数据都会出现预测错误率很低的情况

**Comment by yongzhuo** [comment]
好的，我排查一下问题

**Comment by Veyronl** [comment]
好的,一起查找问题,再次感谢大佬的开源精神和热心回复

**Comment by yongzhuo** [comment]
你是不是没有注意到训练的是acc准确率，预测时候classification_report打印的是pre精确率。这样有比较大的差异是可以解释的，不过确实是效果不好

**Comment by Veyronl** [comment]
训练的时候,训练集和验证集拟合都达到93%左右,
预测用的验证集数据avg / total  0.414937105 0.475409836 0.386892071      1647
挑出训练数据单独测试也是不正确

改了dropout之后准确率就和训练时候一样了吗,我改不改那个预测出的结果是一样的

**Comment by yongzhuo** [comment]
我测试bert和random的embedding是一样的，word2vec的我还没有单独测试过，晚上的时候我下个词向量试试吧。

**Comment by Veyronl** [comment]
![image](https://user-images.githubusercontent.com/46363468/68107174-f1107480-ff1e-11e9-8f02-2403ba00760d.png)
![image](https://user-images.githubusercontent.com/46363468/68107241-24eb9a00-ff1f-11e9-807f-57f8db16e9f9.png)
![image](https://user-images.githubusercontent.com/46363468/68107290-4ba9d080-ff1f-11e9-864b-a4c59fad6dbb.png)
类别有点多

**Comment by Veyronl** [comment]
起初觉得在预测阶段并未使用保存的模型,后来发现配置文件的路径没有问题,模型的保存和加载应该是正确的.
但从预测结果来看,像是模型未有效训练时进行的预测

**Comment by yongzhuo** [comment]
嗯，预测数据没有出现类别特别不均衡的情况，看着不像是。按理说不应该出现这样的训练时候验证数据集的acc和测试时候acc不一样的情况，这个估计还得详细排查下，晚上有时间我再看一下吧。

**Comment by Veyronl** [comment]
好的,麻烦大佬了,最开始我也担心是类别不均衡导致的,输出看过之后否定了猜测;
最重要的是用训练数据去预测也会出错,还挺多,这就很不理解了
查看模型的训练保存,预测句子的输入到表征,到预测,都没有问题,我才更不解的(当然可能只是一个很小的设置问题)

**Comment by yongzhuo** [comment]
没有复现了该问题，重新clone了代码，我用fit_generator训练一个137分类的数据集的时候，如果没有shuffle，训练集的准确率很高，但是验证集的准确率很低。同样的语料，shuffle后验证集的准确率就高了。没有跑出过验证集在训练、测试中存在较大差异的情况。
没有shuffle:
![image](https://user-images.githubusercontent.com/31341349/68190763-fc2fd700-ffe8-11e9-9e29-2c809aeb59ed.png)
shuffle后:
![image](https://user-images.githubusercontent.com/31341349/68190291-1b7a3480-ffe8-11e9-9ac3-15d4e81ddcbb.png)

**Comment by Veyronl** [comment]
大佬,你好,用Word2vec的字向量训练和预测得到的结果是一致的;
词向量得到的结果差异很大,词向量的加载和引用是没有问题的

**Comment by yongzhuo** [comment]
感觉没道理哇，词向量你又没有训练，奇怪。。。
你换一个公开的数据集试试呢，看看会不会出现这样的情况

**Comment by Veyronl** [comment]
谢谢大佬的帮忙;
验证完其他数据集后,基于训练集得到的词向量,做词级别的Word2vec验证集在训练和测试时是一致的;
用这个词向量去训练,我的数据集,也是可以的,训练和测试时正确率一致;
确定是词向量有问题;
重新提取我的语料生成词向量,也没有问题.

目前,问题是解决了,但还是困惑,如果词向量真的有问题,在训练阶段,验证集的准确率应该是一直上不去,而不是训练阶段高,测试阶段低;   困惑ing
