### ISSUE TITLE
Keras-TextClassification-master/keras_textclassification/m04_TextRNN/graph.py

### ISSUE THREAD

**Issue by guo-huojian** [yongzhuo/Keras-TextClassification#21]
Keras-TextClassification-master/keras_textclassification/m04_TextRNN/graph.py
In line 36 to 42 have wrongs,like ''if self.rnn_units=="LSTM" :'' need to be ''if self.rnn_type=="LSTM" :''

**Comment by yongzhuo** [comment]
yes, i will fix it
