### ISSUE TITLE
[CLS] in XLNet should be the last token embedding

### ISSUE THREAD

**Issue by tonywenuon** [yongzhuo/Keras-TextClassification#23]
Hi, 
For the XLNet embedding, I saw the following code:

> x = Lambda(lambda x : x[:, 0:1, :])(embedding_output) # 获取CLS

which is in the graph.py and intends to get the CLS embedding for the following classification task. However, based on the original paper and the demo referring to `https://github.com/CyberZHG/keras-xlnet/blob/master/demo/GLUE/CoLA/cola.py`, the CLS embedding should be the last token embedding. So I assume the code is supposed to change to 

> x = Lambda(lambda x : x[:, -2:-1, :])(embedding_output) # 获取CLS

Please correct me if I'm wrong. Thanks for sharing.

**Comment by yongzhuo** [comment]
yes, i will fix it later!
cola.py:
last = Extract(index=-1, name='Extract')(model.output)
Extract:
def call(self, x, mask=None):
        return x[:, self.index]
