### ISSUE TITLE
安装的前置需求是什么

### ISSUE THREAD

**Issue by Mrzhazha-bignner** [yongzhuo/Keras-TextClassification#28]
在安装keras_textclassificattion的时候把我anaconda里面的tensorflow1.9 keras2.20卸载了。看了一下发现是要tf-gpu吗。
请问对tf和keras的版本要求能不能详细告知

**Comment by yongzhuo** [comment]
也不一定要tf-gpu, cpu的也可以
tensorflow==1.12.0
keras==2.2.4

**Comment by Mrzhazha-bignner** [comment]
好的谢谢

发件人：yongzhuo <notifications@github.com>
发送日期：2020-04-16 22:21:31
收件人：yongzhuo/Keras-TextClassification <Keras-TextClassification@noreply.github.com>
抄送人：Mrzhazha-bignner <31801316@stu.zucc.edu.cn>,Author <author@noreply.github.com>
主题：Re: [yongzhuo/Keras-TextClassification] 安装的前置需求是什么 (#28)

也不一定要tf-gpu, cpu的也可以
 tensorflow==1.12.0
 keras==2.2.4
