### ISSUE TITLE
CapsuleNet中train运行出错

### ISSUE THREAD

**Issue by lvhongyan** [yongzhuo/Keras-TextClassification#29]
请问在运行CapsuleNet中的train是出现错误如下是什么原因  ValueError: Error when checking target: expected dense_1 to have shape (90,) but got array with shape (17,)

**Comment by yongzhuo** [comment]
标签label数不一样，你改一下超参数中的就好。也可能原因是l2i_i2l.json这个缓存没有清除。

**Comment by lvhongyan** [comment]
好的谢谢，是标签数的问题，已经解决了。再次感谢回复



---原始邮件---
发件人: "yongzhuo"<notifications@github.com&gt;
发送时间: 2020年5月6日(周三) 下午2:09
收件人: "yongzhuo/Keras-TextClassification"<Keras-TextClassification@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"lvhongyan"<981220135@qq.com&gt;;
主题: Re: [yongzhuo/Keras-TextClassification] CapsuleNet中train运行出错 (#29)




 
标签label数不一样，你改一下超参数中的就好。也可能原因是l2i_i2l.json这个缓存没有清除。

**Comment by lvhongyan** [comment]
不好意思打扰了，还有一个问题是我看你的博客里提到运行准确率一开始大概只有百分之十几，改过并微调之后就好了，怎么我试运行之后的准确率还是十几呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yongzhuo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 下午2:09
收件人:&nbsp;"yongzhuo/Keras-TextClassification"<Keras-TextClassification@noreply.github.com&gt;;
抄送:&nbsp;"狼外婆"<981220135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yongzhuo/Keras-TextClassification] CapsuleNet中train运行出错 (#29)





 
标签label数不一样，你改一下超参数中的就好。也可能原因是l2i_i2l.json这个缓存没有清除。

**Comment by Sp1cyman** [comment]
> 

同问

**Comment by yongzhuo** [comment]
我试了一下没有问题的。你可以排查下问题。
1. 首先sample数据很少，100条，且分布不均匀，只是样例，你要用多一点语料训练。
2. 直接下载自带的词向量、字向量只有50个，你要用全量的。或者换成'embedding_type': 'random', 'bert'。
3. 此外，你可调节，动态embed  'trainable': True,  学习率'lr': 5e-4,

**Comment by Sp1cyman** [comment]
> @Sp1cyman 我试了一下没有问题的。你可以排查下问题。 主要是下载的词典不全， data/embeddings/term_char.txt term_word.txt w2v_model_merge_short.vec w2v_model_wiki_char.vec 你需要下载全量的覆盖哦
> 
> 其他可能的问题：
> 
> 1. 首先sample数据很少，100条，且分布不均匀，只是样例，你要用多一点语料训练。
> 2. 直接下载自带的词向量、字向量只有50个，你要用全量的。或者换成'embedding_type': 'random', 'bert'。
> 3. 此外，你可调节，动态embed  'trainable': True,  学习率'lr': 5e-4,

百度云给出的data/embeddings和项目中的一样，请问全量的词典在哪里下载呢

**Comment by yongzhuo** [comment]
比如
[https://github.com/Embedding/Chinese-Word-Vectors](https://github.com/Embedding/Chinese-Word-Vectors)
