### ISSUE TITLE
加载错误

### ISSUE THREAD

**Issue by gugudexiatian** [yongzhuo/Keras-TextClassification#4]
windows报错，不晓得为什么
RuntimeError: your input level_type is wrong, it must be 'dict' or 'corpus'

**Comment by yongzhuo** [comment]
讲'embedding': {'layer_indexes': [12], # bert取的层数
                      'corpus_path': '', # embedding预训练数据地址,不配则会默认取conf里边默认的地址
注释掉  'corpus_path': '', # embedding预训练数据地址,不配则会默认取conf里边默认的地址就好
修改后为:
'''
'embedding': {'layer_indexes': [12], # bert取的层数
                      #  'corpus_path': '', # embedding预训练数据地址,不配则会默认取conf里边默认的地址
'''
或者是配置具体的'corpus_path',文件名需要带term或者corpus

**Comment by gugudexiatian** [comment]
嗯嗯，多谢大佬赐教，好使了。
