### ISSUE TITLE
how can I add my own evaluation such as precision and recall

### ISSUE THREAD

**Issue by TaSivan** [yongzhuo/Keras-TextClassification#40]

**Comment by TaSivan** [comment]
dear author，I tried your code with my own evaluation precision and recall，but the output value of p and r are totally same，so I want to turn to your kindness help with how correctly add the evaluation matrix，looking forward to your reply，thank you very
much.

**Comment by yongzhuo** [comment]
you can rewrite keras.callbacks.ModelCheckpoint, like [Kashgari](https://github.com/BrikerMan/Kashgari/blob/v2-main/kashgari/callbacks/eval_callBack.py), or [keras4bert](https://github.com/bojone/bert4keras/blob/master/examples/task_sentiment_albert.py)
