### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by susoooon** [yongzhuo/Keras-TextClassification#41]
数据处理模块。
for _ in epoch（）
while True
读取数据：read
处理：sentence2idx

读取文件是在每轮循环里面，而且如果是word形式，每一条每一轮都要重复分词，效率很低。
建议在循环外面读取数据以及做分词等不需要重复操作的数据处理

**Comment by yongzhuo** [comment]
全量加载数据进入内存的可以，从文件、远程数据库等批量读取可能不行。
