### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by gugudexiatian** [yongzhuo/Keras-TextClassification#5]
感觉这样成体系的代码好棒，如果想改成多标签该如何修改代码呢

**Comment by yongzhuo** [comment]
有时间的话可以试试，你可以看看sklearn机器学习实现[scikit-multilearn](https://github.com/scikit-multilearn/scikit-multilearn)，和[sklearn-hierarchical-classification](https://github.com/globality-corp/sklearn-hierarchical-classification)，详细讲解可以看下这个[解决多标签分类问题(包括案例研究)](https://www.atyun.com/5376.html)。或者是腾讯不久前出的pytorch版[NeuralNLP-NeuralClassifier](https://github.com/Tencent/NeuralNLP-NeuralClassifier)。


简单说明:
1.一般最简单的做法是将多标签问题转化为多类分类问题，就是和普通的分类问题一样，改变一下类别标签就好。这种做法可以看一下看山杯多标签分类比赛的代码，例如[text_classification](https://github.com/brightmart/text_classification)，类别较多的，没有利用类别间的关系。
2.转化为多个分类器问题，就是对每个标签进行分类。每个场景都维护一个神经网络总感觉不爽。
3.或者是近年来的层次分类，似乎还用到了graph知识，这个还没细看。。。

**Comment by gugudexiatian** [comment]
非常感谢您的及时答疑和提供的思路，受益匪浅，感谢感谢！！
