### ISSUE TITLE
acc没有变化

### ISSUE THREAD

**Issue by ZzzD97** [yongzhuo/Keras-TextClassification#54]
无论怎么调整参数，val_acc都没有变化，而且不同模型得到的结果都是一样的，请问怎么回事呢？

**Comment by yongzhuo** [comment]
检查下label个数，数据，输入输出，loss......等对不对呢

**Comment by ZzzD97** [comment]
因为使用自己的数据，更改了label数，loss有变化，但是acc每一轮的结果都一样

**Comment by yongzhuo** [comment]
没有遇见过这样的问题，如果实在有bug，你可以提供一个可复现的example。
