### ISSUE TITLE
执行 sentence_similarity 文件夹下面的 train.py 出现 TypeError: __init__() takes 1 positional argument but 2 were given 错误

### ISSUE THREAD

**Issue by i-wanna-to** [yongzhuo/Keras-TextClassification#56]
大佬，你好！你的项目很棒。

我执行sentence_similarity文件夹下的train.py文件时报错了，但是我不太熟悉这个项目，你可以帮帮我吗？

sentence_similarity文件夹下的train.py文件我只修改了 **'embedding_type': 'bert',**  ，原始是albert，我改成了bert，其他没变化。

报错如下：

graph init ok!
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    train(rate=0.1)
  File "train.py", line 79, in train
    pt = PreprocessSim(path_model_dir)
TypeError: __init__() takes 1 positional argument but 2 were given

train.py文件中前面的代码都可以成功执行，到79行的时候报错了。我看了一下PreprocessSim这个类，初始化函数也没有啥问题。但是我自己解决不了。谢谢了！

**Comment by yongzhuo** [comment]
重新下载项目跑一次，没有遇见该问题。
确保没有 pip install Keras-TextClassification，确保Keras-TextClassification更新到最新，以前的版本text_preprocess.py、generator_preprocess.py可能存在问题。

**Comment by i-wanna-to** [comment]
好的，谢谢！那我关了这个issue了。
