### ISSUE TITLE
博主大大求帮助

### ISSUE THREAD

**Issue by wangzhedaye** [yongzhuo/Keras-TextClassification#57]
Error when checking target: expected dense_1 to have shape (17,) but got array with shape (2,)
我换成自己的数据集做二分类。数据处理好了，但是还需要改什么地方吗，输出的参数你原来是１７分类，现在我需要改哪呀

**Comment by yongzhuo** [comment]
修改hyper_parameters里边的超参数，'label': 2,

**Comment by wangzhedaye** [comment]
提出来后面马上就看到参数啦，忘了提出来。不过还是谢谢博主的热心
