### ISSUE TITLE
同样的数据，xlnet和bert效果差异太大

### ISSUE THREAD

**Issue by TonyKnight13** [yongzhuo/Keras-TextClassification#61]
数据说明：
使用的数据是大佬data包的百度qa数据集
具体是挑选了7个标签，并选各标签500个样本以7:3的比例划分用于训练，测试

遇到的问题：
xlnet的val_acc一直是0.1429，也就是1/7，也就是说效果等同于模型分类的结果一直是同一标签
而bert的val_acc在第一轮就达到了0.8019

这么离谱的结果难道是超参的问题？但超参基本没变动过

**Comment by yongzhuo** [comment]
超参详见:  [ymcui/Chinese-XLNet](https://github.com/ymcui/Chinese-XLNet)
xlnet-base: lr取2e-5或3e-5 等;
memory_len, target_len也配上
