### ISSUE TITLE
下载不聊

### ISSUE THREAD

**Issue by king0903** [yongzhuo/Keras-TextClassification#65]
您好,我的服务器上一直下载不了 pip install Keras-TextClassification但是一直报错;  Rolling back uninstall of scikit-learn
  Moving to /disk01/data/users/zhangmujin/anaconda3/lib/python3.7/site-packages/scikit_learn-0.21.3.dist-info/
   from /disk01/data/users/zhangmujin/anaconda3/lib/python3.7/site-packages/~cikit_learn-0.21.3.dist-info
  Moving to /disk01/data/users/zhangmujin/anaconda3/lib/python3.7/site-packages/sklearn/
   from /disk01/data/users/zhangmujin/anaconda3/lib/python3.7/site-packages/~klearn

请问咱们用的tensorflow是那个版本的 我下载的了tensorflow跑的时候,下载1.版本的话报错是: AttributeError: module 'tensorflow._api.v1.compat.v2' has no attribute '__internal__';;;
版本问题; 在tf.2版本的时候也是报错;

**Comment by yongzhuo** [comment]
配置详见requirements.txt，建议keras==2.2.4, tensorflow==1.12.0，其他的可能会报错

**Comment by yongzhuo** [comment]
配置详见requirements.txt，建议keras==2.2.4, tensorflow==1.12.0，其他的可能会报错
