### ISSUE TITLE
百度云盘的地址重置了

### ISSUE THREAD

**Issue by yaxKai** [yongzhuo/Keras-TextClassification#68]
https://pan.baidu.com/s/1I3vydhmFEQ9nuPG2fDou8Q 这个链接打不开

**Comment by yongzhuo** [comment]
我尝试了一下，并没有重置，需要验证码 rket

**Comment by yaxKai** [comment]
啊 抱歉 是我搞错了

**Comment by zhyongwei** [comment]
> https://pan.baidu.com/s/1I3vydhmFEQ9nuPG2fDou8Q 这个链接打不开

现在这个链接打不开了，下载不了data
