### ISSUE TITLE
'embedding_type': 'bert' 改成bert后报错

### ISSUE THREAD

**Issue by tyn513** [yongzhuo/Keras-TextClassification#71]
pos_embeddings = K.tile(
AttributeError: module 'tensorflow._api.v1.keras.backend' has no attribute 'tile'

目前用的是cpu版本的1.12.0 不知道是不是导致这个问题的原因。。。

**Comment by yongzhuo** [comment]
版本问题，tf用 1.14或者1.15吧，
bert-keras用0.41.0吧
