### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by Allensmile** [yongzhuo/Keras-TextClassification#74]
您好，测试Keras-TextClassification/test/tet_char_bert_embedding.py脚本报错AttributeError: 'tuple' object has no attribute 'layer'，请问是什么问题？谢谢
tf和Keras版本如下：
tf.__version__    '1.15.0'
keras.__version__  '2.2.4'

**Comment by yongzhuo** [comment]
这个是版本问题的报错，试试 tf==1.14， 以及keras-bert==0.41.0呢
