### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_bert.activations'

### ISSUE THREAD

**Issue by Allensmile** [yongzhuo/Keras-TextClassification#76]
您好，测试test/tet_char_albert_embedding.py脚本报错ModuleNotFoundError: No module named 'keras_bert.activations'，请问是什么问题？谢谢
tf、Keras、bert_keras版本如下：
tf.version '1.14.0'
keras.version '2.2.4'
bert_keras.version '0.41.0'

**Comment by yongzhuo** [comment]
已修复，你再重新下一下呢，注意albert版本为 [brightmart/albert_zh](https://github.com/brightmart/albert_zh), google版本权重不支持
