### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by Allensmile** [yongzhuo/Keras-TextClassification#77]
您好，测试test/tet_char_xlnet_embedding.py脚本报错AttributeError: 'tuple' object has no attribute 'layer'，请问是什么问题？谢谢
tf、Keras、bert_keras版本如下：
tf.version '1.14.0'
keras.version '2.2.4'
bert_keras.version '0.41.0'
keras-xlnet.version '0.16.0'
模型：哈工大预训练的中文xlnet模型（chinese_xlnet_mid_L-24_H-768_A-12）

**Comment by yongzhuo** [comment]
keras与tf.keras混用了，因为keras-xlnet只能用tf.keras，

```python
如xlnet源代码的attention.py:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import backend as K
```

你设置一下： os.environ["TF_KERAS"] = "1"，
并且把所有的keras替换为tensorflow.keras
有时间我再修复这个bug
