### ISSUE TITLE
WordEmbedding中具有错误

### ISSUE THREAD

**Issue by li1191863273** [yongzhuo/Keras-TextClassification#8]
WordEmbedding.build()方法

        for word in self.key_vector.index2entity:
            self.token2idx[word] = len(self.token2idx)
            embedding_matrix.append(self.key_vector[word])

如果循环中的word 和原来预定义的 'PAD': 0, 'UNK': 1, 'BOS': 2, 'EOS' 相同，会导致 self.token2idx[word]赋值错误

**Comment by li1191863273** [comment]
但是会导致 self.vocab_size 和 embedding_matrix的size不等，或者直接修改成

        for word in self.key_vector.index2entity:
            if word in self.ot_dict.keys():
                continue
            else:
                self.token2idx[word] = len(self.token2idx)
                embedding_matrix.append(self.key_vector[word])

**Comment by yongzhuo** [comment]
是的,确实可能会存在这样的情况，其他解决办法:
1. 可以对原始语料作lower()操作(全部变为小写)来避规该问题，
2. 或者是设置为'[PAD]': 0, '[UNK]': 1, '[BOS]': 2, '[EOS]':3，这样切词的话就会切开，不会出现冲突问题。修复fix采用的是该方案。

**Comment by li1191863273** [comment]
用的别人训练好的权重，
