### ISSUE TITLE
预训练模型加载问题

### ISSUE THREAD

**Issue by fuguanyu** [yongzhuo/Keras-TextClassification#84]
加载[albert_base_zh](https://storage.googleapis.com/albert_zh/albert_base_zh_additional_36k_steps.zip)预训练模型时，加载的.ckpt文件与预训练模型不一致 请问有没有什么好的办法解决？
![image](https://user-images.githubusercontent.com/104418759/224970883-42b3ffc3-ca4b-4404-a389-f1803e288da3.png)
![image](https://user-images.githubusercontent.com/104418759/224971051-10344045-d31d-450e-8af1-e7db31b83f9e.png)

**Comment by hideinhat** [comment]
> 不支持谷歌的albert的权重, 默认是[https://github.com/brightmart/albert_zh这个，你要用的话只有自己改权重了，就是替换下state_dict的key就好](https://github.com/brightmart/albert_zh%E8%BF%99%E4%B8%AA%EF%BC%8C%E4%BD%A0%E8%A6%81%E7%94%A8%E7%9A%84%E8%AF%9D%E5%8F%AA%E6%9C%89%E8%87%AA%E5%B7%B1%E6%94%B9%E6%9D%83%E9%87%8D%E4%BA%86%EF%BC%8C%E5%B0%B1%E6%98%AF%E6%9B%BF%E6%8D%A2%E4%B8%8Bstate_dict%E7%9A%84key%E5%B0%B1%E5%A5%BD)

请教一下，默认是下图的第三个模型吗？使用第一个albert_tiny_zh需要改权重吗？
![image](https://user-images.githubusercontent.com/61655796/228476183-a263542d-1cb0-4f97-8bbc-7d51f8c9d355.png)

**Comment by yongzhuo** [comment]
应该是的
