### ISSUE TITLE
很费解的一个操作

### ISSUE THREAD

**Issue by li1191863273** [yongzhuo/Keras-TextClassification#9]
模型：FastText
词向量：这个 https://kexue.fm/archives/4304，是word向量不是char向量
数据集是：baike_qa_train.csv、baike_qa_valid.csv

我看训练的时候 ，对文本在BaseEmbedding.sentence2idx 中的处理为
   text = list(jieba.cut(text, cut_all=False, HMM=True))
   例如：人站 在 地球 上 为什么 没有 头朝下 的 感觉       中间的空格会变成''
   这里的样本存在空格，结巴分词会把空格变成''

但是预测的时候，read_and_process方法里面的extract_chinese，会把文本中的空格去掉，然后再结巴分词，训练的时候没有去除空格

为什么训练和预测对文本的处理逻辑不一样

**Comment by yongzhuo** [comment]
是存在这个问题,修复为:


        text = extract_chinese(str(text).upper())
        if self.level_type == 'char':
            text = list(text)
        elif self.level_type == 'word':
            text = list(jieba.cut(text, cut_all=False, HMM=True))

**Comment by li1191863273** [comment]
大哥，我就靠你这一套文本分类代码了

用的时候就一顿操作猛如狗
