### ISSUE TITLE
网盘失效了

### ISSUE THREAD

**Issue by BlackTravel** [yongzhuo/Keras-TextClassification#92]
github项目中只是上传部分数据，需要的前往链接: https://pan.baidu.com/s/1I3vydhmFEQ9nuPG2fDou8Q 提取码: rket
 这个链接失效了

**Comment by yongzhuo** [comment]
见[https://github.com/yongzhuo/Keras-TextClassification/issues/86](https://github.com/yongzhuo/Keras-TextClassification/issues/86)
